"""LaTeX tables for the manuscript, written from the frames paper/analysis.py computes."""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd


def _num(x: float, digits: int = 3) -> str:
    return "--" if x is None or not np.isfinite(x) else f"{x:.{digits}f}"


def _signed(x: float) -> str:
    return "--" if not np.isfinite(x) else f"{x:+.3f}".replace("-", "$-$")


def _pm(mean: float, sd: float) -> str:
    return "--" if not np.isfinite(mean) else f"{mean:.3f}\\,$\\pm$\\,{sd:.3f}"


def _write(path: Path, body: str) -> None:
    path.write_text("% Generated by paper/analysis.py - do not edit.\n" + body, encoding="utf-8")


def composition(out: Path, comp: pd.DataFrame, scoreable: list[str]) -> None:
    rows = []
    for r in comp.itertuples():
        note = "" if r.gene in scoreable else "$^{a}$"
        rows.append(f"{r.gene}{note} & {r.rows:,} & {r.n} & {r.pathogenic} & {r.benign} & {r.expert} & "
                    f"{r.dms:,} & {r.gnomad_observed_pathogenic}/{r.pathogenic} & "
                    f"{r.gnomad_observed_benign}/{r.benign} \\\\")
    total = comp.sum(numeric_only=True)
    rows.append("\\midrule")
    rows.append(f"Total & {int(total.rows):,} & {int(total.n)} & {int(total.pathogenic)} & {int(total.benign)} & "
                f"{int(total.expert)} & {int(total.dms):,} & "
                f"{int(total.gnomad_observed_pathogenic)}/{int(total.pathogenic)} & "
                f"{int(total.gnomad_observed_benign)}/{int(total.benign)} \\\\")
    _write(out / "tab_composition.tex", "\n".join([
        "\\begin{tabular}{lrrrrrrrr}", "\\toprule",
        " & & \\multicolumn{3}{c}{ClinVar ($\\geq$2 stars)} & & & \\multicolumn{2}{c}{In gnomAD} \\\\",
        "\\cmidrule(lr){3-5}\\cmidrule(lr){8-9}",
        "Gene & Substitutions & Labelled & P/LP & B/LB & Expert panel & DMS labels & P/LP & B/LB \\\\",
        "\\midrule", *rows, "\\bottomrule", "\\end{tabular}", ""]))


def feature_axis(out: Path, summary: pd.DataFrame, arms, order, models, model_label, metric: str,
                 name: str) -> None:
    arm = {a.key: a for a in arms}
    s = summary.set_index(["arm", "model"])
    header = " & ".join(model_label[m] for m in models)
    rows = []
    for key in order:
        cells = []
        values = [s.loc[(key, m), f"{metric}_mean"] if (key, m) in s.index else np.nan for m in models]
        best = np.nanmax(values)
        for m, v in zip(models, values):
            if (key, m) not in s.index:
                cells.append("n/a")
                continue
            text = _pm(v, s.loc[(key, m), f"{metric}_sd"])
            cells.append(f"\\textbf{{{text}}}" if np.isclose(v, best) else text)
        rows.append(f"{key} & {arm[key].label} & " + " & ".join(cells) + " \\\\")
    _write(out / f"{name}.tex", "\n".join([
        "\\begin{tabular}{ll" + "c" * len(models) + "}", "\\toprule",
        f"Arm & Features & {header} \\\\", "\\midrule", *rows, "\\bottomrule", "\\end{tabular}", ""]))


def label_axis(out: Path, comparisons: pd.DataFrame, models, model_label, word) -> None:
    c = comparisons.set_index("comparison")
    rows = []
    for m in models:
        cells = []
        for key in ("BThree", "BOne", "BTwo"):
            r = c.loc[f"{key}VsAFive{word(m)}"]
            for metric in ("auc", "mcc"):
                text = (f"{_signed(r[f'{metric}_delta'])} [{_signed(r[f'{metric}_low'])}, "
                        f"{_signed(r[f'{metric}_high'])}]")
                cells.append(f"\\textbf{{{text}}}" if r[f"{metric}_excludes_zero"] else text)
        rows.append(f"{model_label[m]} & " + " & ".join(cells) + " \\\\")
    genes = {k: c.loc[f"{k}VsAFiveGbm", "genes"].replace("+", ", ") for k in ("BThree", "BOne", "BTwo")}
    _write(out / "tab_labels.tex", "\n".join([
        "\\begin{tabular}{lcccccc}", "\\toprule",
        " & \\multicolumn{2}{c}{B3: expert panel only} & \\multicolumn{2}{c}{B1: MSH2 DMS only}"
        " & \\multicolumn{2}{c}{B2: ClinVar + MSH2 DMS} \\\\",
        f" & \\multicolumn{{2}}{{c}}{{({genes['BThree']})}} & \\multicolumn{{2}}{{c}}{{({genes['BOne']})}}"
        f" & \\multicolumn{{2}}{{c}}{{({genes['BTwo']})}} \\\\",
        "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\\cmidrule(lr){6-7}",
        "Model & $\\Delta$AUROC & $\\Delta$MCC & $\\Delta$AUROC & $\\Delta$MCC & $\\Delta$AUROC & $\\Delta$MCC \\\\",
        "\\midrule", *rows, "\\bottomrule", "\\end{tabular}", ""]))


def baselines(out: Path, base: pd.DataFrame, summary: pd.DataFrame, scoreable: list[str], model_label,
              arms) -> None:
    arm = {a.key: a for a in arms}
    rows = []
    for r in base.itertuples():
        per = " & ".join(_num(getattr(r, f"auc_{g}")) for g in scoreable)
        rows.append(f"{r.label} & {per} & {_num(r.auc)} [{_num(r.low)}, {_num(r.high)}] \\\\")
    rows.append("\\midrule")
    s = summary.set_index(["arm", "model"])
    for key, model in (("M", "gbm"), ("M", "mlp"), ("A5", "gbm"), ("A5", "mlp")):
        r = s.loc[(key, model)]
        rows.append(f"{model_label[model]}, {arm[key].label} ({key}) & "
                    + " & ".join("" for _ in scoreable)
                    + f" & {_num(r.auc_mean)} [{_num(r.auc_ci_low)}, {_num(r.auc_ci_high)}] \\\\")
    _write(out / "tab_baselines.tex", "\n".join([
        "\\begin{tabular}{l" + "c" * len(scoreable) + "c}", "\\toprule",
        "Score (no training on labels) & " + " & ".join(scoreable) + " & Mean [95\\% CI] \\\\",
        "\\midrule", *rows, "\\bottomrule", "\\end{tabular}", ""]))


def observed(out: Path, obs: pd.DataFrame, arms, model_label) -> None:
    arm = {a.key: a for a in arms}
    names = {"neg_log_af": "$-\\log_{10}$ gnomAD AF (no training)",
             "alphamissense": "AlphaMissense (no training)", "esm1b": "ESM-1b masked marginal (no training)"}
    rows = []
    for r in obs.itertuples():
        label = names[r.model] if r.condition == "baseline" else f"{model_label[r.model]}, {arm[r.condition].label} ({r.condition})"
        rows.append(f"{label} & {_num(r.auc_all)} [{_num(r.all_low)}, {_num(r.all_high)}] & "
                    f"{_num(r.auc_observed)} [{_num(r.observed_low)}, {_num(r.observed_high)}] \\\\")
    _write(out / "tab_observed.tex", "\n".join([
        "\\begin{tabular}{lcc}", "\\toprule",
        "Predictor & All held-out variants & Variants observed in gnomAD \\\\", "\\midrule",
        *rows, "\\bottomrule", "\\end{tabular}", ""]))


def model_vs_gbm(out: Path, comparisons: pd.DataFrame, models, model_label, word) -> None:
    c = comparisons.set_index("comparison")
    rows = []
    for m in models:
        if m == "gbm":
            continue
        cells = []
        for key in ("M", "AFive"):
            r = c.loc[f"{word(m)}VsGbm{key}"]
            for metric in ("auc", "mcc"):
                text = (f"{_signed(r[f'{metric}_delta'])} [{_signed(r[f'{metric}_low'])}, "
                        f"{_signed(r[f'{metric}_high'])}]")
                cells.append(f"\\textbf{{{text}}}" if r[f"{metric}_excludes_zero"] else text)
        rows.append(f"{model_label[m]} & " + " & ".join(cells) + " \\\\")
    _write(out / "tab_model_vs_gbm.tex", "\n".join([
        "\\begin{tabular}{lcccc}", "\\toprule",
        " & \\multicolumn{2}{c}{M: gnomAD + AlphaMissense} & \\multicolumn{2}{c}{A5: all feature sources} \\\\",
        "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}",
        "Model & $\\Delta$AUROC & $\\Delta$MCC & $\\Delta$AUROC & $\\Delta$MCC \\\\",
        "\\midrule", *rows, "\\bottomrule", "\\end{tabular}", ""]))


def feature_deltas(out: Path, comparisons: pd.DataFrame, models, model_label, word) -> None:
    c = comparisons.set_index("comparison")
    rows = []
    for key, label in (("AOne", "A1 gnomAD"), ("ATwo", "A2 AlphaMissense"), ("AThree", "A3 structure"),
                       ("AFour", "A4 genomic"), ("M", "M gnomAD + AlphaMissense")):
        cells = []
        for m in models:
            name = f"{key}VsAFive{word(m)}"
            if name not in c.index:
                cells.append("--")
                continue
            r = c.loc[name]
            text = _signed(r.auc_delta)
            cells.append(f"\\textbf{{{text}}}" if r.auc_excludes_zero else text)
        rows.append(f"{label} & " + " & ".join(cells) + " \\\\")
    _write(out / "tab_feature_deltas.tex", "\n".join([
        "\\begin{tabular}{l" + "c" * len(models) + "}", "\\toprule",
        "Arm $-$ A5 & " + " & ".join(model_label[m] for m in models) + " \\\\", "\\midrule",
        *rows, "\\bottomrule", "\\end{tabular}", ""]))


def supplementary_arms(out: Path, summary: pd.DataFrame, arms, models, model_label) -> None:
    order = [a.key for a in arms]
    arm = {a.key: a for a in arms}
    s = summary.copy()
    s["_a"] = s.arm.map(order.index)
    s["_m"] = s.model.map(models.index)
    rows = []
    for r in s.sort_values(["_a", "_m"]).itertuples():
        rows.append(f"{r.arm} & {model_label[r.model]} & {r.genes.replace('+', ', ')} & "
                    f"{_pm(r.auc_mean, r.auc_sd)} & {_pm(r.mcc_mean, r.mcc_sd)} & {_pm(r.pr_auc_mean, r.pr_auc_sd)} & "
                    f"{_pm(r.brier_mean, r.brier_sd)} & {_pm(r.ece_mean, r.ece_sd)} \\\\")
    _write(out / "tab_supp_arms.tex", "\n".join([
        "\\begin{longtable}{llllccccc}",
        "\\caption{Every arm and model: mean over the held-out genes listed, $\\pm$ SD over three seeds. "
        "Brier score and ECE are reported as trained; the models use class-weighted losses, so these "
        "measure the weighting as well as the model.}\\label{tab:supp-arms}\\\\",
        "\\toprule", "Arm & Model & Held-out genes & AUROC & MCC & PR-AUC & Brier & ECE \\\\", "\\midrule",
        "\\endfirsthead", "\\toprule", "Arm & Model & Held-out genes & AUROC & MCC & PR-AUC & Brier & ECE \\\\",
        "\\midrule", "\\endhead", *rows, "\\bottomrule", "\\end{longtable}", ""]))


def supplementary_per_gene(out: Path, per_gene: pd.DataFrame, arms, models, model_label) -> None:
    order = [a.key for a in arms]
    g = (per_gene.groupby(["arm", "model", "gene"]).agg(auc=("auc", "mean"), sd=("auc", "std"), n=("n", "first"),
                                                         npos=("n_pathogenic", "first")).reset_index())
    genes = ["MLH1", "MSH2", "MSH6", "PMS2"]
    sizes = g.drop_duplicates("gene").set_index("gene")
    head = " & ".join(f"{x} ($n$={int(sizes.loc[x, 'n'])})" for x in genes if x in sizes.index)
    rows = []
    for (a, m), block in sorted(g.groupby(["arm", "model"]), key=lambda kv: (order.index(kv[0][0]),
                                                                            models.index(kv[0][1]))):
        b = block.set_index("gene")
        cells = [(_pm(b.loc[x, "auc"], b.loc[x, "sd"]) if x in b.index else "not trainable") for x in genes]
        rows.append(f"{a} & {model_label[m]} & " + " & ".join(cells) + " \\\\")
    _write(out / "tab_supp_per_gene.tex", "\n".join([
        "\\begin{longtable}{llcccc}",
        "\\caption{AUROC per held-out gene (mean $\\pm$ SD over three seeds). PMS2 ($n$=21, 4 benign) is "
        "reported but never enters a headline mean.}\\label{tab:supp-per-gene}\\\\",
        "\\toprule", f"Arm & Model & {head} \\\\", "\\midrule", "\\endfirsthead",
        "\\toprule", f"Arm & Model & {head} \\\\", "\\midrule", "\\endhead",
        *rows, "\\bottomrule", "\\end{longtable}", ""]))


def b1_sensitivity(out: Path, sens: pd.DataFrame, arms, model_label) -> None:
    arm = {a.key: a for a in arms}
    rows = [f"{model_label[r.model]}, {arm[r.arm].label} ({r.arm}) & {_num(r.auc_all)} & {_num(r.auc_without_b1)} & "
            f"{_signed(r.change)} \\\\" for r in sens.itertuples()]
    _write(out / "tab_b1.tex", "\n".join([
        "\\begin{tabular}{lccc}", "\\toprule",
        "Cell & AUROC, all & AUROC, affected variants removed & Change \\\\", "\\midrule",
        *rows, "\\bottomrule", "\\end{tabular}", ""]))


def write_all(out: Path, summary, per_gene, base, comparisons, comp, obs, sens, arms, feature_order,
              label_order, models, model_label, scoreable, dms_genes, word) -> None:
    composition(out, comp, scoreable)
    feature_axis(out, summary, arms, feature_order, models, model_label, "auc", "tab_features_auc")
    feature_axis(out, summary, arms, feature_order, models, model_label, "mcc", "tab_features_mcc")
    label_axis(out, comparisons, models, model_label, word)
    baselines(out, base, summary, scoreable, model_label, arms)
    observed(out, obs, arms, model_label)
    model_vs_gbm(out, comparisons, models, model_label, word)
    feature_deltas(out, comparisons, models, model_label, word)
    supplementary_arms(out, summary, arms, models, model_label)
    supplementary_per_gene(out, per_gene, arms, models, model_label)
    b1_sensitivity(out, sens, arms, model_label)
